services:
  nodalpy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WS_URL=ws://127.0.0.1:8555/ws
    container_name: nodalpy_server
    ports:
      - "8555:8000"
    volumes:
      - nodalpy_storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
      - NODAL_DEBOUNCE=300
      - NODAL_BATCH_INTERVAL=50
    restart: unless-stopped

volumes:
  nodalpy_storage:
